### ISSUE TITLE
How can we integrate job with postgres  in docker? 

### ISSUE THREAD

**Issue by daveyesha** [andrespp/docker-pdi#3]
My job is to transfer data of one table say sample1 to another table say sample2 in one job . I configured postgres by making compose file but it did'nt work. It shows me this
![Error 21-10-2019](https://user-images.githubusercontent.com/42044571/67189486-f09ab880-f40b-11e9-8177-27f5c951691e.PNG)
 error

**Comment by andrespp** [comment]
Please make sure that your database is accessible inside de docker-pdi container
